(define dim 7)
(define mat1 (matrix dim dim 0))
(set-matrix! mat1 (lambda(i j)(+ j (* dim i))))
(print 1 "mat1:\n")
(print-matrix 1 mat1)
(print 1 "transpose mat1:\n")
(print-matrix 1 (transpose mat1))
(print 1 "multiply mat1 x mat1:\n")
(print-matrix 1 (multiply (transpose mat1) mat1))

