
(define(vector n val)
	(if (equal? n 0)
		'()
		(cons val (vector (- n 1) val))))

(define(matrix m n val)
	(if (equal? m 0)
		'()
		(cons (vector n val) (matrix (- m 1) n val))))

(define(set-matrix! mat fn)
	(define(set-vector1 vec j fn)
		(if (null? vec)
			'()
			((lambda()
				(set-car! vec (fn j))
				(set-vector1 (cdr vec) (+ j 1) fn)))))
	(define(set-matrix1 mat i fn)
		(if (null? mat)
			'()
			((lambda()
				(set-vector1 (car mat) 0 (lambda(j)(fn i j)))
				(set-matrix1 (cdr mat) (+ i 1) fn)))))
	(set-matrix1 mat 0 fn))

(define(print-matrix port mat)
	(if (null? mat)
		'()
		((lambda()
			(print port (car mat) "\n")
			(print-matrix port (cdr mat))))))

(define(next-column mat)
	(if (null? mat)
		'()
		(cons (cdr (car mat)) (next-column (cdr mat)))))

(define(column-vector mat)
	(if (null? mat)
		'()
		(cons (car (car mat)) (column-vector (cdr mat)))))

(define(transpose mat)
	(if (null? (car mat))
		'()
		(cons (column-vector mat) (transpose (next-column mat)))))

(define(multiply a b)
	(define(row-column a b)
		(if (null? a)
			'()
			(cons (* (car a) (car (car b))) (row-column (cdr a) (cdr b)))))
	(define(row-mat a b)
		(if (null? (car b))
			'()
			(cons (apply + (row-column a b)) (row-mat a (next-column b)))))
	(define(mat-mat a b)
		(if (null? a)
			'()
			(cons (row-mat (car a) b) (mat-mat (cdr a) b))))
	(mat-mat a b))


(define(transform-sum ls)
	(define(two-sum a b)
		(define sum (+ a b))
		(define tmp0 (- sum b))
		(define tmp1 (- sum tmp0))
		(define tmp2 (- a tmp0))
		(define tmp3 (- b tmp1))
		(cons sum (+ tmp2 tmp3)))
	(define(transform-sum1 ls err)
		(if (null? ls)
			(cons err '())
			((lambda()
				(define sumerr (two-sum (car ls) err))
				(define sum (car sumerr))
				(define err (cdr sumerr))
				(if (equal? err 0.0)
					(transform-sum1 (cdr ls) sum)
				(cons err (transform-sum1 (cdr ls) sum)))))))
	(transform-sum1 (cdr ls) (car ls)))
